# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    grip_group_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - arm1_Joint
      - arm2_Joint
      - arm3_Joint
      - arm4_Joiint
      - arm5_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
grip_group_controller:
  ros__parameters:
    joint: rlink1_Joint