settings_version: 0.0.4
datasets_dir: D:\pycharm\python project\Xian Yu\yolo\yolov8\datasets
weights_dir: weights
runs_dir: runs
uuid: 76e9fb4af77464b6b078ce1bf21387e6bee5906e98f131c23ce679e76bcf70ce
sync: true
api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
