# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller
    - grip_group_controller

  arm_group_controller:
    type: FollowJointTrajectory
    joints:
      - arm1_Joint
      - arm2_Joint
      - arm3_Joint
      - arm4_Joiint
      - arm5_Joint
    action_ns: follow_joint_trajectory
    default: true
  grip_group_controller:
    type: GripperCommand
    joints:
      - rlink1_Joint
    action_ns: gripper_cmd
    default: true